//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.TraditionalSimplifiedWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap")]
    public interface TraditionalSimplifiedWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/toSimplifiedChinese", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string toSimplifiedChinese(string sText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/toSimplifiedChinese", ReplyAction="*")]
        System.Threading.Tasks.Task<string> toSimplifiedChineseAsync(string sText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/toTraditionalChinese", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string toTraditionalChinese(string sText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/toTraditionalChinese", ReplyAction="*")]
        System.Threading.Tasks.Task<string> toTraditionalChineseAsync(string sText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TraditionalSimplifiedWebServiceSoapChannel : WindowsFormsApp2.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TraditionalSimplifiedWebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp2.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap>, WindowsFormsApp2.TraditionalSimplifiedWebService.TraditionalSimplifiedWebServiceSoap {
        
        public TraditionalSimplifiedWebServiceSoapClient() {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraditionalSimplifiedWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string toSimplifiedChinese(string sText) {
            return base.Channel.toSimplifiedChinese(sText);
        }
        
        public System.Threading.Tasks.Task<string> toSimplifiedChineseAsync(string sText) {
            return base.Channel.toSimplifiedChineseAsync(sText);
        }
        
        public string toTraditionalChinese(string sText) {
            return base.Channel.toTraditionalChinese(sText);
        }
        
        public System.Threading.Tasks.Task<string> toTraditionalChineseAsync(string sText) {
            return base.Channel.toTraditionalChineseAsync(sText);
        }
    }
}
